In [1]:
import numpy as np
from test_Pre_Image import get_landmark_from_image 
import cv2

def distance(keypoint,keypoints):
    n = len(keypoints)
    np_1 = np.array([keypoint]*n)
    np_2 = np.array(keypoints)
    return ((np_1[:,0]-np_2[:,0])**2 + (np_1[:,1]-np_2[:,1])**2)**(1/2)

def calculate_distance(keypoints):
    return np.array([distance(i,keypoints) for i in keypoints])

def Diff(img1,img2):
    kp1 = get_landmark_from_image(img1)
    kp2 = get_landmark_from_image(img2)
    d_kp1 = calculate_distance(kp1)
    d_kp2 = calculate_distance(kp2)
    return d_kp1-d_kp2

img_normal = cv2.imread("image_10.jpg")
img_abnormal = cv2.imread("image_31.jpg")
print("Differ")
result = Diff(img_normal,img_abnormal)
print(result)

Differ
[[ 0.         -1.8625565  -0.5137043  ... -1.7116318  -1.3084412
  -1.2078781 ]
 [-1.8625565   0.         -1.6794271  ... -0.20713806  0.01152039
   0.11310959]
 [-0.5137043  -1.6794271   0.         ... -0.48723602 -0.21394348
   0.12395477]
 ...
 [-1.7116318  -0.20713806 -0.48723602 ...  0.         -0.07152367
  -0.60045147]
 [-1.3084412   0.01152039 -0.21394348 ... -0.07152367  0.
   0.55680466]
 [-1.2078781   0.11310959  0.12395477 ... -0.60045147  0.55680466
   0.        ]]


In [2]:
import pandas as pd

# Assuming 'result' is your DataFrame
df = pd.DataFrame(result)

# Set custom column names
custom_column_names = list(range(0, 478))  # Replace with your actual column names
df.columns = custom_column_names

# Set custom row names
custom_row_names = list(range(0, 478)) # Replace with your desired row names
df.index = custom_row_names
df.index.name = "Index"
# Now, your DataFrame has custom row names and custom column names.

# Save the DataFrame to a CSV file
df.to_csv('test.csv', index=True, header=True)

In [4]:
df = pd.read_csv("test.csv")
abs(df)

Index         0         1         2         3         4         5  \
0        0  0.000000  1.862556  0.513704  0.266426  1.712620  0.920918   
1        1  1.862556  0.000000  1.679427  2.179705  0.155645  0.917564   
2        2  0.513704  1.679427  0.000000  0.600895  1.412737  0.490704   
3        3  0.266426  2.179705  0.600895  0.000000  2.128662  1.606064   
4        4  1.712620  0.155645  1.412737  2.128662  0.000000  0.727875   
..     ...       ...       ...       ...       ...       ...       ...   
473    473  1.607254  0.164757  0.325745  0.303104  0.590061  0.876820   
474    474  1.918335  0.367043  0.454361  0.049011  0.728886  0.814636   
475    475  1.711632  0.207138  0.487236  0.577202  0.594208  0.930477   
476    476  1.308441  0.011520  0.213943  0.781979  0.482086  0.987858   
477    477  1.207878  0.113110  0.123955  0.123436  0.386616  0.655884   

            6          7         8  ...       468       469        470  \
0    0.686394   9.015450  0.930664  ...  6.714233  5.556519   7.754433   
1    2.409660  12.008328  2.664871  ...  8.944969  7.618321   9.937527   
2    1.213600   9.310532  1.461624  ...  6.712990  5.560768   7.788460   
3    0.257082  10.541819  0.561165  ...  6.378964  4.934071   7.450344   
4    2.175503  12.594460  2.449337  ...  9.107029  7.672813  10.058342   
..        ...        ...       ...  ...       ...       ...        ...   
473  1.682100   8.886162  3.771744  ...  3.711830  1.949459   4.879013   
474  2.369621   9.619667  4.651253  ...  4.446236  2.682953   5.607529   
475  1.002823   7.776444  3.579319  ...  2.647934  0.932610   3.709541   
476  0.709457   7.838203  2.602632  ...  2.660274  0.899109   3.830650   
477  2.188642   9.805550  3.445816  ...  4.615742  2.828983   5.780678   

           471       472       473       474       475       476       477  
0     8.188904  5.998512  1.607254  1.918335  1.711632  1.308441  1.207878  
1    10.633705  8.295605  0.164757  0.367043  0.207138  0.011520  0.113110  
2     8.219917  5.962036  0.325745  0.454361  0.487236  0.213943  0.123955  
3     8.244091  5.579451  0.303104  0.049011  0.577202  0.781979  0.123436  
4    10.914757  8.509399  0.590061  0.728886  0.594208  0.482086  0.386616  
..         ...       ...       ...       ...       ...       ...       ...  
473   5.671562  2.847351  0.000000  0.734745  0.130508  1.054347  0.470164  
474   6.407459  3.565445  0.734745  0.000000  0.749658  1.789023  0.489946  
475   4.545582  1.891026  0.130508  0.749658  0.000000  0.071524  0.600451  
476   4.618214  1.825863  1.054347  1.789023  0.071524  0.000000  0.556805  
477   6.620800  3.743359  0.470164  0.489946  0.600451  0.556805  0.000000  

[478 rows x 479 columns]

In [5]:
from test import *
result.shape

Differ
[[ 0.         -2.1640358  -1.4020462  ... -0.6619415  -0.23310852
  -0.34938812]
 [-2.1640358   0.         -1.1006927  ...  1.0604782   1.3521118
   1.1725273 ]
 [-1.4020462  -1.1006927   0.         ...  1.4029541   1.7284851
   1.8095856 ]
 ...
 [-0.6619415   1.0604782   1.4029541  ...  0.         -0.17046547
  -0.37582684]
 [-0.23310852  1.3521118   1.7284851  ... -0.17046547  0.
   0.58940506]
 [-0.34938812  1.1725273   1.8095856  ... -0.37582684  0.58940506
   0.        ]]


(478, 478)

In [6]:
import numpy as np

def longest_path_max_sum(matrix):

    # matrix = np.array([[0, 2, 1],
    #                 [2, 0, 6],
    #                 [1, 6, 0]])

    num_rows, num_cols = matrix.shape

    # Create a table to store the maximum sum values
    dp_table = np.zeros((num_rows, num_cols))

    # Initialize the first cell of the table
    dp_table[0, 0] = matrix[0, 0]

    # Fill in the dp_table using dynamic programming
    for i in range(num_rows):
        for j in range(num_cols):
            # Skip the first cell (0,0) since we initialized it already
            if i == 0 and j == 0:
                continue
            from_top = dp_table[i - 1, j] if i > 0 else 0
            from_left = dp_table[i, j - 1] if j > 0 else 0
            dp_table[i, j] = max(from_top, from_left) + matrix[i, j]

    # The value in the bottom-right cell of the dp_table contains the maximum sum
    max_sum = dp_table[num_rows - 1, num_cols - 1]

    # Trace back the path from (2,2) to (0,0)
    i, j = num_rows - 1, num_cols - 1
    path = [(i, j)]
    while i > 0 or j > 0:
        from_top = dp_table[i - 1, j] if i > 0 else float('-inf')
        from_left = dp_table[i, j - 1] if j > 0 else float('-inf')
        if from_top > from_left:
            i -= 1
        else:
            j -= 1
        path.append((i, j))

    # Reverse the path to get it from (0,0) to (2,2)
    path = path[::-1]

    print("Longest path with maximum sum:", path)
    print("Maximum sum:", max_sum)

longest_path_max_sum(abs(result))

Longest path with maximum sum: [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (7, 0), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (34, 2), (34, 3), (34, 4), (34, 5), (34, 6), (34, 7), (34, 8), (34, 9), (34, 10), (34, 11), (34, 12), (34, 13), (34, 14), (34, 15), (34, 16), (34, 17), (34, 18), (34, 19), (34, 20), (35, 20), (36, 20), (36, 21), (37, 21), (38, 21), (39, 21), (40, 21), (41, 21), (42, 21), (43, 21), (44, 21), (44, 22), (44, 23), (44, 24), (44, 25), (44, 26), (44, 27), (44, 28), (44, 29), (44, 30), (44, 31), (44, 32), (44, 33), (44, 34), (45, 34), (46, 34), (47, 34), (48, 34), (49, 34), (50, 34), (51, 34), (51, 35), (51, 36), (52, 36), (52, 37), (53, 37), (54, 37), (54, 38), (54, 39), (54, 40), (54, 41), (54, 42), (54, 43), (54, 44), (54, 45), (54, 46), (54, 47), (54

In [3]:
import os
import numpy as np
from test_Pre_Image import get_landmark_from_image 
import cv2

def distance(keypoint, keypoints):
    n = len(keypoints)
    np_1 = np.array([keypoint] * n)
    np_2 = np.array(keypoints)
    return ((np_1[:, 0] - np_2[:, 0])**2 + (np_1[:, 1] - np_2[:, 1])**2)**0.5

def calculate_distance(keypoints):
    return np.array([distance(i, keypoints) for i in keypoints])

def Diff(img1, img2):
    kp1 = get_landmark_from_image(img1)
    kp2 = get_landmark_from_image(img2)
    d_kp1 = calculate_distance(kp1)
    d_kp2 = calculate_distance(kp2)
    return np.abs(d_kp1 - d_kp2)

def calculate_distance_matrix(folder_path_normal, folder_path_abnormal):
    normal_images = os.listdir(folder_path_normal)
    abnormal_images = os.listdir(folder_path_abnormal)

    num_normal_images = len(normal_images)
    num_abnormal_images = len(abnormal_images)

    distance_matrix = np.zeros((num_normal_images, num_abnormal_images))

    for i, normal_img in enumerate(normal_images):
        img_normal = cv2.imread(os.path.join(folder_path_normal, normal_img))
        for j, abnormal_img in enumerate(abnormal_images):
            img_abnormal = cv2.imread(os.path.join(folder_path_abnormal, abnormal_img))
            result = Diff(img_normal, img_abnormal)
            # distance_matrix[i][j] = np.mean(result)

    return result


folder_path_normal = "Normal"
folder_path_abnormal = "Abnormal"

distance_matrix = calculate_distance_matrix(folder_path_normal, folder_path_abnormal)
print(distance_matrix)


[[ 0.          0.67785645  4.6675987  ... 29.142403   27.458847
  25.852432  ]
 [ 0.67785645  0.          5.351653   ... 28.746254   27.163094
  25.127823  ]
 [ 4.6675987   5.351653    0.         ... 23.948143   22.300621
  20.57798   ]
 ...
 [29.142403   28.746254   23.948143   ...  0.          1.7339525
   3.400032  ]
 [27.458847   27.163094   22.300621   ...  1.7339525   0.
   2.0132837 ]
 [25.852432   25.127823   20.57798    ...  3.400032    2.0132837
   0.        ]]


In [73]:
import numpy as np
from test_Pre_Image import get_landmark_from_image
import cv2
import os

def process_images_in_folder(folder_path):
    
    image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.gif'))]

    landmark_arrays = []
    for image_file in image_files:
        image_path = os.path.join(folder_path, image_file)
        image = cv2.imread(image_path)

        landmarks = get_landmark_from_image(image)
        if landmarks is not None:
            landmark_arrays.append(landmarks)
        else:
            landmark_arrays.append([0])
    return landmark_arrays
folder_path = 'DataSets\\Origin\\Normal'
landmark_arrays_normal = process_images_in_folder(folder_path)



In [74]:
import numpy as np
from test_Pre_Image import get_landmark_from_image
import cv2
import os

def process_images_in_folder(folder_path):
    # Get a list of image files in the folder
    image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.gif'))]

    landmark_arrays = []
    for image_file in image_files:
        image_path = os.path.join(folder_path, image_file)
        image = cv2.imread(image_path)

        landmarks = get_landmark_from_image(image)

        # Check if landmarks were found for the current image
        if landmarks is not None:
            landmark_arrays.append(landmarks)
        else:
            # Append 0 for each keypoint if landmarks were not found
            landmark_arrays.append([0])  # Replace num_keypoints with the actual number of keypoints
    return landmark_arrays

folder_path = 'DataSets\\Origin\\Abnormal'
landmark_arrays_abnormal = process_images_in_folder(folder_path)
len(landmark_arrays_abnormal)


400

In [75]:
def distance(keypoint, keypoints):
    n = len(keypoints)
    np_1 = np.array([keypoint] * n)
    np_2 = np.array(keypoints)
    return np.sqrt((np_1[:, 0] - np_2[:, 0])**2 + (np_1[:, 1] - np_2[:, 1])**2)

def calculate_distance(keypoints):
    return np.array([distance(i, keypoints) for i in keypoints])

distance_matrices_normal = []

for landmarks in landmark_arrays_normal:
    distances = calculate_distance(landmarks)
    distance_matrices_normal.append(distances)
distance_matrices_normal


[array([[  0.      ,  35.359756,  21.985062, ..., 101.687584,  93.47638 ,
          87.50555 ],
        [ 35.359756,   0.      ,  13.456819, ...,  68.13793 ,  59.642662,
          54.79663 ],
        [ 21.985062,  13.456819,   0.      , ...,  81.06377 ,  72.65718 ,
          67.34735 ],
        ...,
        [101.687584,  68.13793 ,  81.06377 , ...,   0.      ,   8.629208,
          14.74902 ],
        [ 93.47638 ,  59.642662,  72.65718 , ...,   8.629208,   0.      ,
           8.711486],
        [ 87.50555 ,  54.79663 ,  67.34735 , ...,  14.74902 ,   8.711486,
           0.      ]], dtype=float32),
 array([[ 0.      , 31.757343, 20.758888, ..., 99.33752 , 91.19882 ,
         84.96935 ],
        [31.757343,  0.      , 11.006586, ..., 69.45561 , 61.034473,
         55.862503],
        [20.758888, 11.006586,  0.      , ..., 79.76419 , 71.439865,
         65.8117  ],
        ...,
        [99.33752 , 69.45561 , 79.76419 , ...,  0.      ,  8.571835,
         14.886697],
        [91.19882 , 6

In [76]:

def distance(keypoint, keypoints):
    n = len(keypoints)
    np_1 = np.array([keypoint] * n)
    np_2 = np.array(keypoints)
    return np.sqrt((np_1[:, 0] - np_2[:, 0])**2 + (np_1[:, 1] - np_2[:, 1])**2)

def calculate_distance(keypoints):
    return np.array([distance(i, keypoints) for i in keypoints])

distance_matrices_abnormal = []

for landmarks in landmark_arrays_abnormal:
    distances = calculate_distance(landmarks)
    distance_matrices_abnormal.append(distances)
len(distance_matrices_abnormal)

400

In [77]:


result_matrices = []
for matrix_abnormal, matrix_normal in zip(distance_matrices_abnormal, distance_matrices_normal):
    if matrix_abnormal.shape == (0, ) or matrix_normal.shape == (0, ):

        continue
    result_matrix = np.array(matrix_normal) - np.array(matrix_abnormal)
    result_matrices.append(result_matrix)

if result_matrices:
    mean_result_matrix = np.mean(result_matrices, axis=0)
    print("Mean Result Matrix:")
    print(mean_result_matrix)
else:
    print("No valid matrices to calculate the mean.")



Mean Result Matrix:
[[ 0.         2.817067   3.4837654 ... 19.827147  17.943975  16.763258 ]
 [ 2.817067   0.        -1.3266423 ... 15.594778  13.482575  12.178775 ]
 [ 3.4837654 -1.3266423  0.        ... 16.448212  14.486995  13.435269 ]
 ...
 [19.827147  15.594778  16.448212  ...  0.         2.0209877  3.0512474]
 [17.943975  13.482575  14.486995  ...  2.0209877  0.         1.9539931]
 [16.763258  12.178775  13.435269  ...  3.0512474  1.9539931  0.       ]]
